### PR TITLE
Fixing API issues

### PR DESCRIPTION
**Pull request by neomarbassani**

### CODE REVIEW

**Comment by michaelcizmar** [comment]
Need a better description

**Comment by aworley** [comment]
Hello,

This commit changes the indent style; replacing the tabs with space characters.  Ideally, I'd prefer to stick with tabs.

Aaron

**Comment by neomarbassani** [comment]
I'm closing this pull request to review indent style.

**Comment by neomarbassani** [comment]
I'm closing this pull request to review indent style.

**Pull request closed without merging**
